"""Add timezone awareness to datetime columns

Revision ID: 1fe85f36a1a5
Revises: 2a7a559e761b
Create Date: 2026-02-24 20:50:39.006034

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "1fe85f36a1a5"
down_revision = "2a7a559e761b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "gamestate",
        "last_updated",
        type_=sa.DateTime(timezone=True),
        existing_type=sa.DateTime(),
    )
    op.alter_column(
        "gamestate_history",
        "timestamp",
        type_=sa.DateTime(timezone=True),
        existing_type=sa.DateTime(),
    )
    op.alter_column(
        "scoreboard",
        "last_updated",
        type_=sa.DateTime(timezone=True),
        existing_type=sa.DateTime(),
    )
    op.alter_column(
        "scoreboard_history",
        "timestamp",
        type_=sa.DateTime(timezone=True),
        existing_type=sa.DateTime(),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "scoreboard_history",
        "timestamp",
        type_=sa.DateTime(),
        existing_type=sa.DateTime(timezone=True),
    )
    op.alter_column(
        "scoreboard",
        "last_updated",
        type_=sa.DateTime(),
        existing_type=sa.DateTime(timezone=True),
    )
    op.alter_column(
        "gamestate_history",
        "timestamp",
        type_=sa.DateTime(),
        existing_type=sa.DateTime(timezone=True),
    )
    op.alter_column(
        "gamestate",
        "last_updated",
        type_=sa.DateTime(),
        existing_type=sa.DateTime(timezone=True),
    )
    # ### end Alembic commands ###
