---
name: CI Jobs

on:
  pull_request:
    branches:
      - master

jobs:
  linter:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: pip3 install --upgrade setuptools wheel
      - run: pip3 install -e .[dev]

      - id: black
        run: black --check .

      - id: pylint
        run: pylint emojirades

    outputs:
      black_conclusion: ${{ steps.black.conclusion }}
      pylint_conclusion: ${{ steps.pylint.conclusion }}

  pytest:
    runs-on: ubuntu-24.04

    needs: linter
    if: ${{ needs.linter.outputs.black_conclusion == 'success' && needs.linter.outputs.pylint_conclusion == 'success' }}

    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - run: pip3 install --upgrade setuptools wheel
      - run: pip3 install -e .[dev]

      - run: ./scripts/run_tests.sh
