---
name: Release jobs

on:
  push:
    branches:    
      - master

jobs:
  release:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      # Create github release
      - id: version
        run: |
          echo "::set-output name=version::$(python setup.py --version)"
          echo "::set-output name=version_with_prefix::v$(python setup.py --version)"

      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version_with_prefix }}
          release_name: Release ${{ steps.version.outputs.version_with_prefix }}
          body: ${{ steps.tag_version.outputs.changelog }}

      # Build and push python package
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - run: python setup.py sdist bdist_wheel

      - name: upload sdist
        id: upload_sdist
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/Emojirades-${{ steps.version.outputs.version }}.tar.gz
          asset_name: Emojirades-${{ steps.version.outputs.version }}.tar.gz
          asset_content_type: application/tar+gzip

      - name: upload bdist_wheel
        id: upload_bdist_wheel
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/Emojirades-${{ steps.version.outputs.version }}-py3-none-any.whl
          asset_name: Emojirades-${{ steps.version.outputs.version }}-py3-none-any.whl
          asset_content_type: application/x-pywheel+zip

      - uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      # Build and push container image
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags:
            emojirades/emojirades:latest
            emojirades/emojirades:${{ steps.version.outputs.version }}
